/* GENERAL LOADING */
export const START_GENERAL_LOADING = 'START_GENERAL_LOADING'
export const STOP_GENERAL_LOADING = 'STOP_GENERAL_LOADING'

/* GENERAL NOTIFICATION */
export const SHOW_GENERAL_NOTIFICATION = 'SHOW_GENERAL_MESSAGE'
