/* GENERAL LOADING */
export const START_GENERAL_LOADING = 'START_GENERAL_LOADING'
export const STOP_GENERAL_LOADING = 'STOP_GENERAL_LOADING'

/* GENERAL MESSAGE */
export const SHOW_GENERAL_MESSAGE = 'SHOW_GENERAL_MESSAGE'
export const DISMISS_GENERAL_MESSAGE = 'DISMISS_GENERAL_MESSAGE'