export const GET_USERS = 'GET_USERS';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const RESET_USERS = 'RESET_USERS';

export const GET_USER = 'GET_USER';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';

export const CREATE_USER = 'CREATE_USER';

export const UPDATE_USER = 'UPDATE_USER';

export const CHANGE_PASSWORD_USER = 'CHANGE_PASSWORD_USER';

export const REMOVE_USER = 'REMOVE_USER';
export const REMOVE_USER_SUCCESS = 'REMOVE_USER_SUCCESS';
