/* AUTH */
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';

export const SET_DATA_AFTER_RELOADING = 'SET_DATA_AFTER_RELOADING';
export const SET_DATA_AFTER_RELOADING_SUCCESS = 'SET_DATA_AFTER_RELOADING_SUCCESS';

export const GET_PERMISSIONS = 'GET_PERMISSIONS';
export const GET_PERMISSIONS_SUCCESS = 'GET_PERMISSIONS_SUCCESS';

export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED';

export const LOGOUT_USER = 'LOGOUT_USER';

export const FORGET_PASSWORD = 'FORGET_PASSWORD';
export const FORGET_PASSWORD_SUCCESS = 'FORGET_PASSWORD_SUCCESS';

// export const CHANGE_FORGOT_PASSWORD = 'CHANGE_FORGOT_PASSWORD';
// export const CHANGE_FORGOT_PASSWORD_SUCCESS = 'CHANGE_FORGOT_PASSWORD_SUCCESS';
// export const CHANGE_FORGOT_PASSWORD_FAILED = 'CHANGE_FORGOT_PASSWORD_FAILED';
// export const CHANGE_FORGOT_PASSWORD_FIELDS_FAILED = 'CHANGE_FORGOT_PASSWORD_FIELDS_FAILED';
